from __future__ import annotations

from dataclasses import dataclass


LEGACY_IP_HOST = "200.129.244.212"
OLD_SUBDOMAIN_SUFFIX = ".antigoportal.ifmt.edu.br"
OLD_SUBDOMAIN_MAIN_HOST = "antigoportal.ifmt.edu.br"

DEFAULT_HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/124.0 Safari/537.36"
    ),
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Accept-Language": "pt-BR,pt;q=0.9,en;q=0.8",
    "Connection": "keep-alive",
}


@dataclass(frozen=True)
class SourceConfig:
    source_id: str
    source_name: str
    source_type: str
    source_environment: str
    base_url: str
    news_archive_url: str
    source_access_mode: str
    ssl_verify: bool
    campus_code: str | None = None
    campus_name: str | None = None
    notes: str = ""


DEFAULT_DIAGNOSTIC_SOURCES: tuple[SourceConfig, ...] = (
    SourceConfig(
        source_id="legacy_ip_https",
        source_name="IFMT legacy portal by IP HTTPS",
        source_type="legacy_ip",
        source_environment="legacy_ip_portal",
        base_url="https://200.129.244.212",
        news_archive_url="https://200.129.244.212/conteudo/noticias/",
        source_access_mode="ip",
        ssl_verify=False,
        notes="Mandatory historical source. HTTPS certificate is expected not to match the IP.",
    ),
    SourceConfig(
        source_id="legacy_ip_http",
        source_name="IFMT legacy portal by IP HTTP",
        source_type="legacy_ip",
        source_environment="legacy_ip_portal",
        base_url="http://200.129.244.212",
        news_archive_url="http://200.129.244.212/conteudo/noticias/",
        source_access_mode="ip",
        ssl_verify=False,
        notes="HTTP fallback for the mandatory historical source.",
    ),
    SourceConfig(
        source_id="legacy_domain",
        source_name="IFMT legacy listing by domain",
        source_type="legacy_domain",
        source_environment="legacy_domain_listing",
        base_url="https://ifmt.edu.br",
        news_archive_url="https://ifmt.edu.br/conteudo/noticias/",
        source_access_mode="domain",
        ssl_verify=True,
        notes="Diagnostic listing source. Individual historical articles may fail on this host.",
    ),
    SourceConfig(
        source_id="current_portal",
        source_name="IFMT current WordPress portal",
        source_type="current_wordpress",
        source_environment="current_wordpress_portal",
        base_url="https://ifmt.edu.br",
        news_archive_url="https://ifmt.edu.br/blog/categoria/noticias/",
        source_access_mode="domain",
        ssl_verify=True,
    ),
    SourceConfig(
        source_id="campus_cba",
        source_name="IFMT Campus Cuiaba",
        source_type="campus_wordpress",
        source_environment="campus_current_portal",
        base_url="https://cba.ifmt.edu.br",
        news_archive_url="https://cba.ifmt.edu.br/categoria/noticias/",
        source_access_mode="domain",
        ssl_verify=True,
        campus_code="cba",
        campus_name="Campus Cuiaba",
    ),
    SourceConfig(
        source_id="campus_bag",
        source_name="IFMT Campus Barra do Garcas",
        source_type="campus_wordpress",
        source_environment="campus_current_portal",
        base_url="https://bag.ifmt.edu.br",
        news_archive_url="https://bag.ifmt.edu.br/categoria/noticias/",
        source_access_mode="domain",
        ssl_verify=True,
        campus_code="bag",
        campus_name="Campus Barra do Garcas",
    ),
)


DISCOVERY_SOURCES: dict[str, SourceConfig] = {
    "legacy_ip": SourceConfig(
        source_id="legacy_ip",
        source_name="IFMT legacy portal by IP",
        source_type="legacy_ip",
        source_environment="legacy_ip_portal",
        base_url="https://200.129.244.212",
        news_archive_url="https://200.129.244.212/conteudo/noticias/",
        source_access_mode="ip",
        ssl_verify=False,
        notes="Mandatory historical source. Preserve IP as URL base.",
    ),
    "current_portal": SourceConfig(
        source_id="current_portal",
        source_name="IFMT current WordPress portal",
        source_type="current_wordpress",
        source_environment="current_wordpress_portal",
        base_url="https://ifmt.edu.br",
        news_archive_url="https://ifmt.edu.br/blog/categoria/noticias/",
        source_access_mode="domain",
        ssl_verify=True,
    ),
    "campus_cba": SourceConfig(
        source_id="campus_cba",
        source_name="IFMT Campus Cuiaba",
        source_type="campus_wordpress",
        source_environment="campus_current_portal",
        base_url="https://cba.ifmt.edu.br",
        news_archive_url="https://cba.ifmt.edu.br/categoria/noticias/",
        source_access_mode="domain",
        ssl_verify=True,
        campus_code="cba",
        campus_name="Campus Cuiaba",
    ),
    "campus_bag": SourceConfig(
        source_id="campus_bag",
        source_name="IFMT Campus Barra do Garcas",
        source_type="campus_wordpress",
        source_environment="campus_current_portal",
        base_url="https://bag.ifmt.edu.br",
        news_archive_url="https://bag.ifmt.edu.br/categoria/noticias/",
        source_access_mode="domain",
        ssl_verify=True,
        campus_code="bag",
        campus_name="Campus Barra do Garcas",
    ),
    "campus_pdl": SourceConfig(
        source_id="campus_pdl",
        source_name="IFMT Campus Primavera do Leste",
        source_type="campus_wordpress",
        source_environment="campus_current_portal",
        base_url="https://pdl.ifmt.edu.br",
        news_archive_url="https://pdl.ifmt.edu.br/categoria/noticias/",
        source_access_mode="domain",
        ssl_verify=True,
        campus_code="pdl",
        campus_name="Campus Primavera do Leste",
    ),
    "campus_svc": SourceConfig(
        source_id="campus_svc",
        source_name="IFMT Campus Sao Vicente",
        source_type="campus_wordpress",
        source_environment="campus_current_portal",
        base_url="https://svc.ifmt.edu.br",
        news_archive_url="https://svc.ifmt.edu.br/categoria/noticias/",
        source_access_mode="domain",
        ssl_verify=True,
        campus_code="svc",
        campus_name="Campus Sao Vicente",
    ),
    "oldportal_main": SourceConfig(
        source_id="oldportal_main",
        source_name="IFMT antigoportal main",
        source_type="old_subdomain_portal",
        source_environment="old_subdomain_portal",
        base_url="https://antigoportal.ifmt.edu.br",
        news_archive_url="https://antigoportal.ifmt.edu.br/noticias/",
        source_access_mode="old_subdomain",
        ssl_verify=False,
        campus_code="antigoportal_main",
        campus_name="Reitoria",
        notes="Historical old subdomain portal. Preserve original host.",
    ),
    "oldportal_cba": SourceConfig(
        source_id="oldportal_cba",
        source_name="IFMT antigoportal Campus Cuiaba",
        source_type="old_subdomain_portal",
        source_environment="old_subdomain_portal",
        base_url="https://cba.antigoportal.ifmt.edu.br",
        news_archive_url="https://cba.antigoportal.ifmt.edu.br/noticias/",
        source_access_mode="old_subdomain",
        ssl_verify=False,
        campus_code="cba",
        campus_name="Campus Cuiabá",
    ),
    "oldportal_svc": SourceConfig(
        source_id="oldportal_svc",
        source_name="IFMT antigoportal Campus Sao Vicente",
        source_type="old_subdomain_portal",
        source_environment="old_subdomain_portal",
        base_url="https://svc.antigoportal.ifmt.edu.br",
        news_archive_url="https://svc.antigoportal.ifmt.edu.br/noticias/",
        source_access_mode="old_subdomain",
        ssl_verify=False,
        campus_code="svc",
        campus_name="Campus São Vicente",
    ),
    "oldportal_lrv": SourceConfig(
        source_id="oldportal_lrv",
        source_name="IFMT antigoportal Campus Lucas do Rio Verde",
        source_type="old_subdomain_portal",
        source_environment="old_subdomain_portal",
        base_url="https://lrv.antigoportal.ifmt.edu.br",
        news_archive_url="https://lrv.antigoportal.ifmt.edu.br/noticias/",
        source_access_mode="old_subdomain",
        ssl_verify=False,
        campus_code="lrv",
        campus_name="Campus Lucas do Rio Verde",
    ),
    "oldportal_tga": SourceConfig(
        source_id="oldportal_tga",
        source_name="IFMT antigoportal Campus Tangara da Serra",
        source_type="old_subdomain_portal",
        source_environment="old_subdomain_portal",
        base_url="https://tga.antigoportal.ifmt.edu.br",
        news_archive_url="https://tga.antigoportal.ifmt.edu.br/noticias/",
        source_access_mode="old_subdomain",
        ssl_verify=False,
        campus_code="tga",
        campus_name="Campus Tangará da Serra",
    ),
    "oldportal_bag": SourceConfig(
        source_id="oldportal_bag",
        source_name="IFMT antigoportal Campus Barra do Garcas",
        source_type="old_subdomain_portal",
        source_environment="old_subdomain_portal",
        base_url="https://bag.antigoportal.ifmt.edu.br",
        news_archive_url="https://bag.antigoportal.ifmt.edu.br/noticias/",
        source_access_mode="old_subdomain",
        ssl_verify=False,
        campus_code="bag",
        campus_name="Campus Barra do Garças",
    ),
    "oldportal_pdl": SourceConfig(
        source_id="oldportal_pdl",
        source_name="IFMT antigoportal Campus Primavera do Leste",
        source_type="old_subdomain_portal",
        source_environment="old_subdomain_portal",
        base_url="https://pdl.antigoportal.ifmt.edu.br",
        news_archive_url="https://pdl.antigoportal.ifmt.edu.br/noticias/",
        source_access_mode="old_subdomain",
        ssl_verify=False,
        campus_code="pdl",
        campus_name="Campus Primavera do Leste",
    ),
    "oldportal_cfs": SourceConfig(
        source_id="oldportal_cfs",
        source_name="IFMT antigoportal Campus Confresa",
        source_type="old_subdomain_portal",
        source_environment="old_subdomain_portal",
        base_url="https://cfs.antigoportal.ifmt.edu.br",
        news_archive_url="https://cfs.antigoportal.ifmt.edu.br/noticias/",
        source_access_mode="old_subdomain",
        ssl_verify=False,
        campus_code="cfs",
        campus_name="Campus Confresa",
    ),
    "oldportal_cas": SourceConfig(
        source_id="oldportal_cas",
        source_name="IFMT antigoportal Campus Caceres",
        source_type="old_subdomain_portal",
        source_environment="old_subdomain_portal",
        base_url="https://cas.antigoportal.ifmt.edu.br",
        news_archive_url="https://cas.antigoportal.ifmt.edu.br/noticias/",
        source_access_mode="old_subdomain",
        ssl_verify=False,
        campus_code="cas",
        campus_name="Campus Cáceres",
    ),
    "oldportal_blv": SourceConfig(
        source_id="oldportal_blv",
        source_name="IFMT antigoportal Campus Cuiaba - Bela Vista",
        source_type="old_subdomain_portal",
        source_environment="old_subdomain_portal",
        base_url="https://blv.antigoportal.ifmt.edu.br",
        news_archive_url="https://blv.antigoportal.ifmt.edu.br/noticias/",
        source_access_mode="old_subdomain",
        ssl_verify=False,
        campus_code="blv",
        campus_name="Campus Cuiabá - Bela Vista",
    ),
}

DISCOVERY_SOURCE_GROUPS: dict[str, tuple[str, ...]] = {
    "legacy_ip": ("legacy_ip",),
    "current": ("current_portal",),
    "campuses": ("campus_cba", "campus_bag", "campus_pdl", "campus_svc"),
    "antigoportal": (
        "oldportal_main",
        "oldportal_cba",
        "oldportal_svc",
        "oldportal_lrv",
        "oldportal_tga",
        "oldportal_bag",
        "oldportal_pdl",
        "oldportal_cfs",
        "oldportal_cas",
        "oldportal_blv",
    ),
    "old_subdomain_portal": (
        "oldportal_main",
        "oldportal_cba",
        "oldportal_svc",
        "oldportal_lrv",
        "oldportal_tga",
        "oldportal_bag",
        "oldportal_pdl",
        "oldportal_cfs",
        "oldportal_cas",
        "oldportal_blv",
    ),
    "all": (
        "legacy_ip",
        "current_portal",
        "campus_cba",
        "campus_bag",
        "campus_pdl",
        "campus_svc",
        "oldportal_main",
        "oldportal_cba",
        "oldportal_svc",
        "oldportal_lrv",
        "oldportal_tga",
        "oldportal_bag",
        "oldportal_pdl",
        "oldportal_cfs",
        "oldportal_cas",
        "oldportal_blv",
    ),
}
